import { StyleSheet } from "react-native";

export default StyleSheet.create({
  modalView: {
    position: "absolute",
    height: "93.9%",
    width: "100%",
    top: "6%",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
  },
  topGreyLine: {
    position: "absolute",
    width: "13.6%",
    height: 3,
    borderRadius: 12,
    backgroundColor: "#C4C4C4",
    top: "1.6%",
    left: "43.2%",
  },
  exitPressable: {
    position: "absolute",
    top: "1.8%",
    right: "4.2%",
    display: "flex",
    justifyContent: "center",
    alignContent: "center",
    width: 36,
    height: 19,
  },
  closeText: {
    color: "#526DC2",
  },
  title: {
    position: "absolute",
    top: "8.7%",
    left: "37.6%",
    width: "25.06%",
    textAlign: "center",
  },
  profileImage: {
    position: "absolute",
    display: "flex",
    alignItems: "center",
    width: "100%",
    top: "14.6%",
    height: "17.6%",
  },
  profileImagePressable: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    left: "31.35%",
    top: "14%",
    width: "37.333%",
    height: "17.03%",
    borderRadius: 10,
    borderStyle: "solid",
    borderColor: "#F2F2F2",
    borderWidth: 2,
  },
  fields: {
    display: "flex",
    justifyContent: "space-between",
    position: "absolute",
    left: "8.2%",
    top: "38.4%",
    height: "9.96%",
  },
  nameField: {
    position: "absolute",
    left: "8.26%",
    //top: "38.4%",
    bottom: "59.2%",
  },
  emailField: {
    position: "absolute",
    left: "8.26%",
    //top: "45.87%",
    bottom: "51.63%",
  },

  nameTextInput: {
    position: "absolute",
    top: "37.09%",
    left: "29%",
    width: "61%",
    height: "5.1%",
    borderColor: "#A9A9A9",
    borderWidth: 1,
    fontSize: 16,
    paddingLeft: "5%",
    borderRadius: 5,
  },
  emailTextInput: {
    position: "absolute",
    top: "44.56%",
    left: "29%",
    width: "61%",
    height: "5.1%",
    borderColor: "#A9A9A9",
    borderWidth: 1,
    fontSize: 16,
    paddingLeft: "5%",
    borderRadius: 5,
  },
  savePressable: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    left: "7.47%",
    top: "52%",
    width: "85.06%",
    height: "6.1%",
    borderRadius: 10,
    borderStyle: "solid",
    backgroundColor: "#A9A9A9",
  },
  savePressableAllowed: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    left: "7.47%",
    top: "52%",
    width: "85.06%",
    height: "6.1%",
    borderRadius: 10,
    borderStyle: "solid",
    backgroundColor: "#253C85",
  },
  whiteText: {
    color: "#FFFFFF",
  },
});
