import { StyleSheet } from "react-native";

export default StyleSheet.create({
  modalView: {
    position: "absolute",
    height: "93.9%",
    width: "100%",
    top: "6%",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
  },
  topGreyLine: {
    position: "absolute",
    width: "13.6%",
    height: 3,
    borderRadius: 12,
    backgroundColor: "#C4C4C4",
    top: "1.6%",
    left: "43.2%",
  },
  exitPressable: {
    position: "absolute",
    top: "1.8%",
    right: "4.2%",
    display: "flex",
    justifyContent: "center",
    alignContent: "center",
    width: 36,
    height: 19,
  },
  closeText: {
    color: "#526DC2",
  },
  title: {
    textAlign: "center",
    position: "absolute",
    top: "8.7%",
    left: "38.6%",
    width: 94,
  },
  profileImage: {
    position: "absolute",
    display: "flex",
    alignItems: "center",
    width: "100%",
    top: "14.6%",
    height: "17.6%",
  },
  profileImagePressable: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    left: "31.2%",
    top: "14%",
    width: 140,
    height: 130,
    borderRadius: 10,
    borderStyle: "solid",
    borderColor: "#F2F2F2",
    borderWidth: 2,
  },
  fields: {
    display: "flex",
    justifyContent: "space-between",
    position: "absolute",
    left: "8.2%",
    top: "39%",
    height: "10%",
  },
  nameTextInput: {
    position: "absolute",
    top: "37.8%",
    left: "29%",
    width: "61%",
    height: "4%",
    borderColor: "#A9A9A9",
    borderWidth: 1,
    fontSize: 16,
    paddingLeft: "5%",
    borderRadius: 5,
  },
  textRoleInput: {
    position: "absolute",
    bottom: "50%",
    left: "29%",
    width: "61%",
    height: "4%",
    borderColor: "#A9A9A9",
    borderWidth: 1,
    fontSize: 16,
    paddingLeft: "5%",
    borderRadius: 5,
  },
  savePressable: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    left: "31.2%",
    top: "55%",
    width: 140,
    height: 30,
    borderRadius: 10,
    borderStyle: "solid",
    borderColor: "#F2F2F2",
    borderWidth: 2,
  },
});
