import { StyleSheet } from "react-native";

export default StyleSheet.create({
  modalView: {
    position: "absolute",
    height: "93.9%",
    width: "100%",
    top: "6%",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
  },
  topGreyLine: {
    position: "absolute",
    width: "13.6%",
    height: 3,
    borderRadius: 12,
    backgroundColor: "#C4C4C4",
    top: "1.6%",
    left: "43.2%",
  },
  exitPressable: {
    position: "absolute",
    top: "3.2%",
    right: "8.9%",
    display: "flex",
    justifyContent: "center",
    alignContent: "center",
    width: 20,
    height: 20,
  },
  resetPasswordTitle: {
    position: "absolute",
    top: "11.4%",
    left: "10%",
    width: "81.3%",
  },
  subText1: {
    position: "absolute",
    top: "19%",
    left: "10%",
    width: "81.3%",
  },
  subText2: {
    position: "absolute",
    top: "26.7%",
    left: "10%",
    width: "81.3%",
  },
  emailInput: {
    position: "absolute",
    top: "33.5%",
    left: "10%",
    width: "81.3%",
    height: "5%",
    borderBottomColor: "#A9A9A9",
    borderBottomWidth: 2,
    fontSize: 16,
  },
  verifyInput: {
    position: "absolute",
    top: "31%",
    left: "10%",
    width: "81.3%",
    height: "5%",
    borderBottomColor: "#A9A9A9",
    borderBottomWidth: 2,
    fontSize: 16,
  },
  setNewInput: {
    position: "absolute",
    top: "21%",
    left: "10%",
    width: "81.3%",
    height: "5%",
    borderBottomColor: "#A9A9A9",
    borderBottomWidth: 2,
    fontSize: 16,
  },
  confirmNewInput: {
    position: "absolute",
    top: "31%",
    left: "10%",
    width: "81.3%",
    height: "5%",
    borderBottomColor: "#A9A9A9",
    borderBottomWidth: 2,
    fontSize: 16,
  },
  resetContinuePressable: {
    display: "flex",
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    top: "50%",
    width: "81.3%",
    left: "10%",
    height: "5%",
    backgroundColor: "#C4C4C4",
    borderRadius: 5,
    opacity: 0.5,
  },
  resetContinuePressableAllowed: {
    display: "flex",
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    top: "50%",
    width: "81.3%",
    left: "10%",
    height: "5%",
    backgroundColor: "#C4C4C4",
    borderRadius: 5,
  },
  resendPressable: {
    display: "flex",
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    top: "45.2%",
    width: "81.3%",
    left: "10%",
    height: "5%",
    backgroundColor: "#C4C4C4",
    borderRadius: 5,
  },
  verifyContinuePressable: {
    display: "flex",
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    top: "51.3%",
    width: "81.3%",
    left: "10%",
    height: "5%",
    backgroundColor: "#C4C4C4",
    borderRadius: 5,
    opacity: 0.5,
  },
  verifyContinuePressableAllowed: {
    display: "flex",
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    top: "51.3%",
    width: "81.3%",
    left: "10%",
    height: "5%",
    backgroundColor: "#C4C4C4",
    borderRadius: 5,
  },
  closePressable: {
    display: "flex",
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    top: "31.9%",
    width: "81.3%",
    left: "10%",
    height: "5%",
    backgroundColor: "#C4C4C4",
    borderRadius: 5,
  },
  mustBeCharacter: {
    position: "absolute",
    top: "27%",
    right: "9.3%",
    color: "#A9A9A9",
    fontFamily: "Avenir",
    fontSize: 12,
    fontStyle: "normal",
    fontWeight: "400",
    height: 16,
    textAlign: "left",
  },
  pwMustMatch: {
    position: "absolute",
    top: "37%",
    right: "9.3%",
    color: "#A9A9A9",
    fontFamily: "Avenir",
    fontSize: 12,
    fontStyle: "normal",
    fontWeight: "400",
    height: 16,
    textAlign: "left",
  },
  passwordHiddenIconSet: {
    position: "absolute",
    top: "23%",
    right: "11%",
  },
  passwordHiddenIconConfirm: {
    position: "absolute",
    top: "33%",
    right: "11%",
  },
});
