import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  switchProfileModalView: {
    position: 'absolute',
    width: '92.5%',
    height: '46%',
    top: '20%',
    left: '4%',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#F2F2F2',
  },
  switchModalX: {
    display: 'flex',
    position: 'absolute',
    top: '5%',
    right: '5%',
  },
  flatListItem: {
    display: 'flex',
    alignContent: 'center',
    justifyContent: 'center',
    width: '100%',
    marginVertical: 15,
  },
  listInfo: {
    display: 'flex',
    left: '21.9%',
  },
  itemSeparator: {
    height: '0%',
    width: '74%',
    borderStyle: 'solid',
    borderColor: '#F2F2F2',
    borderWidth: 1,
    left: '21.9%',
  },
  lastItemSeparator: {
    height: '0%',
    width: '74%',
    borderStyle: 'solid',
    borderColor: '#F2F2F2',
    borderWidth: 1,
    left: '21.9%',
    position: 'relative',
    top: '-90%', //hard fix for last separator but try better way 
  },
  signedIn: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F2F2F2',
    width: '21.6%',
    height: 24,
    position: 'absolute',
    right: '4%',
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#A9A9A9",
    borderStyle: 'solid',
  },
  switch: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 24,
    width: '16.7%',
    position: 'absolute',
    right: '4%',
    backgroundColor: '#7F93D1',
    borderRadius: 26,
  },
  switchTitle: {
    position: 'absolute',
    left: '17%',
    top: "5%",
    textAlign: 'center',
    width: '64%'
  },
  flatList: {
    position: 'absolute',
    top: 63,
    width: '100%',
    height: '84%',
  },
  flatListImagePressable: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: '4%',
    width: 42,
    height: 42,
  },
  addMember: {
    display: 'flex',
    justifyContent: 'center',
    alignContent: 'center',
    marginTop: 18,
  },
  body2WHITE: {
    fontFamily: "DMSans_400Regular",
    fontSize: 12,
    fontWeight: "400",
    textAlign: "left",
    color: "#FFFFFF"
  },
});
