import { StyleSheet } from "react-native";

export default StyleSheet.create({
    profileName: {
        position: "absolute",
        top: "24%",
        textAlign: "center",
        //fontFamily: "DM Sans", dont have dm sans need to import?
        fontStyle: "normal",
        fontWeight: "bold",
        fontSize: 24,
        lineHeight: 31,

        color: "#525454",
    },
    profileImage: {
        display: "flex",
        justifyContent: "center",
        alignContent: "center",
        position:"absolute",
    },
    editPressable: {
        display: "flex",
        position: "absolute",
        alignItems: "center",
        justifyContent: "center",
        width: "40%",
        height: "5%",
        top: "30%",
        left: "8%",
        backgroundColor: "#F2F2F2",
    },
    resetPressable: {
        display: "flex",
        position: "absolute",
        top: "30%",
        right: "8%",
        alignItems: "center",
        justifyContent: "center",
        width: "40%",
        height: "5%",
        backgroundColor: "#F2F2F2", 
    },
    fields: {
        fontFamily: "Avenir",
        fontSize: 14,
        fontWeight: "900",
        lineHeight: 19,
        textTransform: "uppercase",
        color: "#525454",
    },
    values: {
        fontFamily: "Avenir",
        fontSize: 14,
        lineHeight: 19,
        color: "#525454",
    },
    profileFields: {
        display: "flex",
        flexDirection: "column",
        position: "absolute",
        left: "8%",
        top: "39.6%",
        height: "23%",
        justifyContent: "space-between",
    },
    profileValues: {
        display: "flex",
        flexDirection: "column",
        position: "absolute",
        left: "37%",
        top: "39.6%",
        height: "23%",
        justifyContent: "space-between",
    },
    buttonText: {
        fontFamily: "Avenir",
        fontWeight: "800",
        fontSize: 12,
        lineHeight: 16,
        color: "#525454",
    },
    logoutPressable: {
        display: "flex",
        position: "absolute",
        alignItems: "center",
        justifyContent: "center",
        top:"77%",
        width: "40%",   
        height: "5%",
        backgroundColor: "#C4C4C4",
    },
    profileImagePressable: {
        display: "flex",
        position: "absolute",
        alignItems: "center",
        justifyContent: "center",
        top: "6%",
        width: "37%",
        height: "16%",
        backgroundColor: "#FAFAFA",
        borderRadius: 10,
    }, 
    switchProfileModalView: {
        position: "absolute",
        width: "87%",
        height: "46%",
        top: "20%",
        left: "6%",
        backgroundColor: "#E3E3E3",
        borderRadius: 10,


    }
})