import { StyleSheet } from "react-native";

export default StyleSheet.create({
  backArrowPressable: {
    position: "absolute",
    top: "8%",
    left: "8.1%",
  },
  profileImagePressable: {
    display: "flex",
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    top: "8.8%",
    width: "37.3%",
    height: "16%",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    borderColor: "#F2F2F2",
    borderWidth: 2,
    borderStyle: "solid",
  },
  profileImage: {
    display: "flex",
    justifyContent: "center",
    alignContent: "center",
  },
  profileName: {
    position: "absolute",
    top: "26.8%",
    textAlign: "center",
  },
  editPressable: {
    display: "flex",
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    width: "42.9%",
    height: "5%",
    top: "33.1%",
    left: "5.3%",
    backgroundColor: "#7F93D1",
    borderRadius: 5,
  },
  overline2WHITE: {
    fontFamily: "Avenir",
    fontWeight: "800",
    fontSize: 12,
    textTransform: "uppercase",
    textAlign: "left",
    color: "#FFFFFF",
  },
  resetPressable: {
    display: "flex",
    position: "absolute",
    top: "33.1%",
    right: "5.3%",
    alignItems: "center",
    justifyContent: "center",
    width: "42.9%",
    height: "5%",
    backgroundColor: "#C9C8C8",
    borderRadius: 5,
  },
  profileFields: {
    display: "flex",
    flexDirection: "column",
    position: "absolute",
    left: "8%",
    top: "43%",
    height: "15.8%",
    justifyContent: "space-between",
  },
  profileValues: {
    display: "flex",
    flexDirection: "column",
    position: "absolute",
    left: "37%",
    top: "43%",
    height: "15.8%",
    justifyContent: "space-between",
  },
  overline1WHITE: {
    fontFamily: "Avenir",
    fontWeight: "900",
    fontSize: 14,
    textTransform: "uppercase",
    textAlign: "left",
    color: "#FFFFFF",
  },
  logoutPressable: {
    display: "flex",
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    top: "84.9%",
    width: "89.3%",
    height: "5.7%",
    backgroundColor: "#253C85",
    borderRadius: 5,
  },
  modalVisibleContainer: {
    flex: 1,
    backgroundColor: "#000000",
    width: "100%",
    height: "100%",
    opacity: 0.4,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  downArrow: {
    position: "absolute",
    bottom: "6%",
  },
});
