name: Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: yarn 
      - name: check linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
