name: Actions

on: [push, pull_request]

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn 
      
      - name: Run Linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
          auto_fix: ${{ github.event_name == 'pull_request' }}
          git_name: Auto-Lint-Fixer
