name: Actions

on:
  push:
    paths-ignore:
      - README.md
      - .github/workflows/rating-chart.yml
  pull_request:
    paths-ignore:
      - README.md
      - .github/workflows/rating-chart.yml

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn 
      
      - name: Run Linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
          auto_fix: true
          git_name: Auto-Lint-Fixer
