name: Actions

on: [push, pull_request]

jobs:
  runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn 
      - name: Run Linter
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
